@url = http://localhost:3035

### simple users READ
GET {{url}}/simpleUsers
content-type: application/json

### simple users CREATE
POST {{url}}/simpleUsers/create
content-type: application/json
 
{
    "firstName": "Andre",
    "lastName": "Hackerkrug"
}

### simple users UPDATE
PATCH {{url}}/simpleUsers/update/619e0fbf2a641d90d72bab17
content-type: application/json
 
{
    "lastName": "Lastname-Changed"
}


### simple users DELETE
DELETE {{url}}/simpleUsers/delete/619e0fbf2a641d90d72bab17
content-type: application/json



### nested users READ
GET {{url}}/nestedUsers
content-type: application/json